language: python

cache: pip
sudo: required
dist: xenial

python:
  - "2.7"
  - "3.5"

cache:
  directories:
    - /home/travis/virtualenv/python2.7/lib/python2.7/site-packages

before_install:
    - pip install coveralls

script:
    - coverage run --source=abraham setup.py test

after_script:
  - flake8 abraham

after_success:
  - coveralls
